# Generated by Django 2.2 on 2019-06-12 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("accounts", "0002_user_motto")]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to="media/account/photoes/%Y/%D"
            ),
        )
    ]
