# Generated by Django 2.2 on 2019-10-14 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("accounts", "0004_auto_20190617_2031")]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="date_of_birth",
            field=models.DateField(
                blank=True, null=True, verbose_name="birthday"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="motto",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="motto"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="nickname",
            field=models.CharField(
                blank=True, max_length=32, null=True, verbose_name="nickname"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="real_name",
            field=models.CharField(
                blank=True, max_length=32, null=True, verbose_name="real name"
            ),
        ),
    ]
