# Generated by Django 2.2 on 2019-10-20 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("accounts", "0006_auto_20191020_1523")]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to="account/photos/%Y/%M"
            ),
        )
    ]
