# Generated by Django 2.1.4 on 2019-01-28 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0005_auto_20190127_1612"),
        ("articles", "0006_auto_20190127_1632"),
    ]

    operations = []
