# Generated by Django 2.2 on 2019-06-09 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("articles", "0007_merge_20190128_1202")]

    operations = [
        migrations.AddField(
            model_name="article", name="raw", field=models.TextField(null=True)
        )
    ]
