const articlesConstants = {
  RECEIVE_USER: "RECEIVE_USER",
  GET_TAG_LIST: "GET_TAG_LIST",
  RECEIVE_ARTICLE_INSTANCE: "RECEIVE_ARTICLE_INSTANCE",
  RECEIVE_ARTICLE_LIST: "RECEIVE_ARTICLE_LIST"
};
export default articlesConstants;
