# Generated by Django 2.2 on 2019-10-20 07:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='created',
        ),
        migrations.AddField(
            model_name='tag',
            name='ctime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='mtime',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
    ]
