# Generated by Django 2.2 on 2019-10-21 02:48

from django.db import migrations, models
import resources.models


class Migration(migrations.Migration):

    dependencies = [("resources", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="upload",
            field=models.FileField(
                upload_to=resources.models.resource_directory_path
            ),
        )
    ]
