# Generated by Django 2.2 on 2019-10-21 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("resources", "0002_auto_20191021_1048")]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="filetype",
            field=models.CharField(
                choices=[("IMAGE", "image"), ("ATTACHMENT", "attachment")],
                default="IMAGE",
                max_length=10,
            ),
        )
    ]
