const articlesConstants = {
  RECEIVE_USER: "RECEIVE_USER",
  GET_TAG_LIST: "GET_TAG_LIST",
  RECEIVE_ARTICLE_INSTANCE: "RECEIVE_ARTICLE_INSTANCE",
  RECEIVE_ARTICLE_LIST: "RECEIVE_ARTICLE_LIST",
  UPDATE_ARTICLE_EDITOR: "UPDATE_ARTICLE_EDITOR"
};
export default articlesConstants;
